### ISSUE TITLE
Support ReverseLayout 

### ISSUE THREAD

**Issue by wongcain** [nanihadesuka/LazyColumnScrollbar#10]
Using this with a LazyColumn where `reverseLayout=true` results in the scrollbar going from top-to-bottom instead of bottom-to-top.  It should be an easy enhancement to add support for reversing the top/bottom positions.  (I may follow-up with a PR if I can find time.)

**Comment by nanihadesuka** [comment]
@wongcain done 0a2b7b5dbad74d0428e7f6160decd2ce24ddd846 (didn't do it in a PR but oh well :D)
