### ISSUE TITLE
documentation on usage not 100% correct.

### ISSUE THREAD

**Issue by zaifrun** [nanihadesuka/LazyColumnScrollbar#11]
On the gitpage it gives this usage example:

LazyColumnScrollbar(listState = listState) {
        LazyColumn(....)
}

Howver, since this actually matches two different signatures of the composable named LazyColumnScrollbar (as the name is overloaded), it will not compile in Android Studio.

I had to do this: 
LazyColumnScrollbar(listState = listState, enabled = true) {
    LazyColumn(....)

}
as this only matches one composable signature to get it to work.
Otherwise, great library!

**Comment by nanihadesuka** [comment]
4546263e792ddd7560379f2a8c7dea2386aec040
