### ISSUE TITLE
Possible to remove androidx.constraintlayout:constraintlayout-compose

### ISSUE THREAD

**Issue by hmy65** [nanihadesuka/LazyColumnScrollbar#24]
First, thanks for this awesome library.
If it can only depend on Column/Box/Row to build the layout, that would be quite nice.

**Comment by hmy65** [comment]
Done. For anyone who does not want import constraintlayout-compose, cuz this dependency increases roughly ~110kb to the release build.

    BoxWithConstraints(
        modifier = modifier
            .fillMaxWidth()
    ) {
        val maxHeightFloat = constraints.maxHeight.toFloat()
        Row(
            modifier = Modifier
                .align(if (rightSide) Alignment.TopEnd else Alignment.TopStart)
                .graphicsLayer(
                    translationX = with(LocalDensity.current) { (if (rightSide) displacement.dp else -displacement.dp).toPx() },
                    translationY = maxHeightFloat * normalizedOffsetPosition
                )
        ) {
//            val (box, content) = createRefs()

            //  if (indicatorContent != null) {
            Box(
                modifier = Modifier
                    .alpha(alpha)
//                        .constrainAs(content) {
//                            top.linkTo(box.top)
//                            bottom.linkTo(box.bottom)
//                            if (rightSide) end.linkTo(box.start)
//                            else start.linkTo(box.end)
//                        }
                    .testTag(TestTagsScrollbar.scrollbarIndicator),
            ) {
                //indicatorContent(firstVisibleItemIndex.value, isSelected)
                Text(text = firstVisibleItemIndex.value.toString())
            }
            //  }

            Box(
                modifier = Modifier
//                    .align(if (rightSide) Alignment.TopEnd else Alignment.TopStart)
//                    .graphicsLayer(
//                        translationX = with(LocalDensity.current) { (if (rightSide) displacement.dp else -displacement.dp).toPx() },
//                        translationY = maxHeightFloat * normalizedOffsetPosition
//                    )
                    .padding(
                        start = if (rightSide) 0.dp else padding,
                        end = if (!rightSide) 0.dp else padding,
                    )
                    .clip(thumbShape)
                    .width(thickness)
                    .fillMaxHeight(normalizedThumbSize)
                    .alpha(alpha)
                    .background(if (isSelected) thumbSelectedColor else thumbColor)
//                    .constrainAs(box) {
//                        if (rightSide) end.linkTo(parent.end)
//                        else start.linkTo(parent.start)
//                    }
                    .testTag(TestTagsScrollbar.scrollbar)
            )


        }

**Comment by nanihadesuka** [comment]
Will check out

**Comment by nanihadesuka** [comment]
The code you provided removes functionality and is a regression. For know I will keep the ConstraintLayout as I don't want to reinvent the functionality it provides for this case.

In case you provide a full working PR without ConstraintLayout I will merge.
