### ISSUE TITLE
Can't download 2.0.1

### ISSUE THREAD

**Issue by Kyant0** [nanihadesuka/LazyColumnScrollbar#34]
<img width="242" alt="image" src="https://github.com/nanihadesuka/LazyColumnScrollbar/assets/76829190/2aa1c663-1372-4580-b418-c6e93ffff248">

The jar is empty

**Comment by phucynwa** [comment]
Please fix this @nanihadesuka

**Comment by nanihadesuka** [comment]
Checking, seems the migration from groovy to kotlin for gradle is wonky.

**Comment by nanihadesuka** [comment]
Fixed with 2.0.7 (hopefully)
