### ISSUE TITLE
Can we add an option to customise Scrollbar hide animation

### ISSUE THREAD

**Issue by MSVhora** [nanihadesuka/LazyColumnScrollbar#35]
I checked the docs, there is no option to change hide animation of the scrollbar. If possible can you add that option?

**Comment by sergionettl** [comment]
What part of the animation, the animation curve, speed or all ?

**Comment by MSVhora** [comment]
If we can give option to change the whole animation, that would be ideal. Animation duration is already there. I just wanted fadeout animation instead of the current one

**Comment by nanihadesuka** [comment]
@MSVhora added some couple parameters in 5406b969bdb4945bb9bae604ea60270f50f6983c

There are now 4 parameters you can control:
  - hideDelayMillis
  - hideDisplacement
  - hideEasingAnimation
  - durationAnimationMillis
  
Is this enough options?

**Comment by MSVhora** [comment]
> @MSVhora added some couple parameters in [5406b96](https://github.com/nanihadesuka/LazyColumnScrollbar/commit/5406b969bdb4945bb9bae604ea60270f50f6983c)
> 
> There are now 4 parameters you can control:
> 
> * hideDelayMillis
> * hideDisplacement
> * hideEasingAnimation
> * durationAnimationMillis
> 
> Is this enough options?

@nanihadesuka Thanks for the quick fix, these properties is what I needed. I needed to just fade the scrollbar, I can do that by passing `0.dp` in `hideDisplacement`. When are you planning a release?

**Comment by nanihadesuka** [comment]
https://github.com/nanihadesuka/LazyColumnScrollbar/releases/tag/2.1.0
