### ISSUE TITLE
No options to set a fixed thumb size

### ISSUE THREAD

**Issue by Funambol-Android-Developers** [nanihadesuka/LazyColumnScrollbar#37]
It would be great to have an option to set a fixed thumb size, regardless of the list size

**Comment by nanihadesuka** [comment]
Are you sure you don't mean min thumb size? Having a fixed thumb size defeats the purpose of the scroll as it doesn't represent the "percentage" of visible screen. It would also create alot of edge case UX issues when the thumb can't really scroll down as the page is already scrolled.

**Comment by nanihadesuka** [comment]
Let me think about it.

**Comment by Funambol-Android-Developers** [comment]
Hi @nanihadesuka,

thank you for your prompt feedback!

I would like to avoid having a very long bar when you have few items... I think it could be the same also having a "max thumb size", but IMO the fixed thumb size would be better.

**Comment by nanihadesuka** [comment]
Added max thumb length in 994a35e . If you set both the min and max the same value it will do what you want.

**Comment by Funambol-Android-Developers** [comment]
It works like a charm! Thank you very much @nanihadesuka

**Comment by Funambol-Android-Developers** [comment]
@nanihadesuka actually I just realized that if I change the thumbMaxLength the scrollbar doesn't move to the bottom of the list

**Comment by nanihadesuka** [comment]
Expected behaviour :=). Already mentioned in my previous comment this would happen.

 > Having a fixed thumb size defeats the purpose of the scroll as it doesn't represent the "percentage" of visible screen. It would also create alot of edge case UX issues when the thumb can't really scroll down as the page is already scrolled.

You can't scroll down a list that is already scrolled down (fully visible top and bottom).
