### ISSUE TITLE
Option to ignore the initially horizontal dragging in vertical scrollbars

### ISSUE THREAD

**Issue by Kyant0** [nanihadesuka/LazyColumnScrollbar#38]
This would be helpful if you use navigation gestures. If we don't prevent the scrollbars for the horizontal gestures, it will scroll firstly and then navigate back, which impacts user experience.

**Comment by nanihadesuka** [comment]
Could you word it differently? Please, give me some use case examples of the issue, so I can see what solutions could work.

**Comment by Kyant0** [comment]
Vertical scrollbars should only respond to the vertical dragging. If we do horizontal dragging on it (for example the gesture that swipe left to go back), we should disable the action of scrollbars.

**Comment by nanihadesuka** [comment]
Vertical scrollbars only respond to vertical gestures, are you sure this is what you meant?
A video would be helpful in case is hard to explain with words

**Comment by nanihadesuka** [comment]
Closing as the original issue isn't clear.
