### ISSUE TITLE
Make scrollbar only react to touches on knob 

### ISSUE THREAD

**Issue by savvasdalkitsis** [nanihadesuka/LazyColumnScrollbar#4]
Currently touching anywhere on the scrollbar gutter will move the scrollbar under your finger, making pressing back on phones with gesture navigation mess up the scroll position.

I feel like the scrollbar should only react to touch events when the knob is visible and when the initiating gesture starts on the knob itself

**Comment by nanihadesuka** [comment]
67a83c1c2dee26b2f97b53561c976b6ea1ed7c9e

**Comment by savvasdalkitsis** [comment]
Hm I don't think this is working unless I misunderstood what it's supposed to do. Setting selection mode to thumb still scrolls my column when I touch on the gutter outside the thumb

**Comment by nanihadesuka** [comment]
Yes, I missed that case, sorry. I did it too fast without looking at all the edge cases.

**Comment by nanihadesuka** [comment]
677be1cb3dc4202d5109d60d20b77b7e7a37bb0d this should fix it.
Feel free to close this issue when you are satisfied with the results.

**Comment by savvasdalkitsis** [comment]
This fixes it! thanks for the quick updates, it's greatly appreciated
