### ISSUE TITLE
Add compose desktop support

### ISSUE THREAD

**Issue by Wavesonics** [nanihadesuka/LazyColumnScrollbar#9]
It would be great to have this with multi-platform support!

**Comment by nanihadesuka** [comment]
As the readme says, this implementation is for jetpack compose not compose desktop but we can look at it and make it multiplatform. Can you provide what is currently not compatible of this repo with compose desktop?

**Comment by NobilityDeviant** [comment]
> As the readme says, this implementation is for jetpack compose not compose desktop but we can look at it and make it multiplatform. Can you provide what is currently not compatible of this repo with compose desktop?

The only current issues i'm seeing is the use of ConstraintLayout
It's not added to multiplatform yet and probably won't be for awhile.

Would there be anyway to get around it?

**Comment by zacharee** [comment]
I reworked the layout to use `Box` instead of `ConstraintLayout` and commonized some of the code here: https://github.com/zacharee/SamloaderKotlin/tree/master/common/src/commonMain/kotlin/my/nanihadesuka/compose.

It's not fully tested, but it seems to work with what I've tried.

**Comment by nanihadesuka** [comment]
@Wavesonics dependency on constraints lib removed refactor in : 675c62ebe7eb7b0018d48ec6a981b7fc778a4cc8

**Comment by nanihadesuka** [comment]
Version 2.0.0 is out. Closing ticket as solved.
